### PR TITLE
Structure folder for platforms

### PR DESCRIPTION
**Pull request by tobiolo**

### CODE REVIEW

**Comment by aardappel** [comment]
can you rebase?

**Comment by tobiolo** [comment]
> can you rebase?

Yes, I did.

**Comment by aardappel** [comment]
I don't see the advantage of putting a `platforms` dir in between, this creates hierarchy where none is needed, given that we have so few dirs anyway. You can instead improve the existing code structure by just renaming the `treesheets` dir to `win64` or better just `win` since `linux` and `osx` don't specify their bit-width either :) We don't have `win32` builds anymore.

**Comment by aardappel** [comment]
yup looks good!

**Pull request merged**
