### PR TITLE
Added a question mark as a 48x48 PNG and the SVG used to generate it to /TS/images.

### PR DESCRIPTION
**Pull request by arizvisa**
This is for one of the 2 feature requests from issue #94.

I had an issue with testing this against the "March 2017" version which is the binary that I'm using. The "March 2017" binary is using 16x16 icons, but the repository includes 64x64 icons. Was the "March 2017" binary just using an older icon set, or does Treesheets scale the images down?

I left the .png and the .svg used to generate it in /TS/images in case you wanted to tweak it, or if you wanted to add .svg to .png conversion as part of the build.

### CODE REVIEW

**Comment by aardappel** [comment]
Thanks! You placed it in `TS/images` though, where it won't be picked up by the code. It should probably be in `TS/images/nuvola/dropdown`.
Not sure if we need the .svg, since the other images don't have one either.

**Comment by arizvisa** [comment]
Ok, I just threw out the .svg then. I included it since it was used to render the image and since on older versions of Treesheets the icon size was 16x16 and in the repo it's now 64x64. If the image sizes change then there's no way to generate the icon for the correct size.

**Comment by arizvisa** [comment]
I dropped the .png in the images directory because it crashes TreeSheets on my binary with a null dereference, which is why i mentioned the difference in sizes. I figured you'd want to test it on your build before you move it into the directory. But I dropped it into the nuvola directory like mentioned in the issue.

**Comment by aardappel** [comment]
Well, why is it crashing? If you don't understand, at least post some details like a stack trace. Pull request are supposed to be complete and tested.

**Comment by arizvisa** [comment]
Umm....

https://github.com/aardappel/treesheets/pull/102#issue-172349951
```
...
I had an issue with testing this against the "March 2017" version which is the binary that I'm using. The "March 2017" binary is using 16x16 icons, but the repository includes 64x64 icons. Was the "March 2017" binary just using an older icon set, or does Treesheets scale the images down?
...
```

https://github.com/aardappel/treesheets/pull/102#issuecomment-369769301
```
I dropped the .png in the images directory because it crashes TreeSheets on my binary with a null dereference, which is why i mentioned the difference in sizes. I figured you'd want to test it on your build before you move it into the directory.
```

**Comment by arizvisa** [comment]
Not sure why you'd want to debug an older binary, but it looks like one of the objects has a property that's uninitialized at %ecx+34. Base address is at 0x400000. According to an assertion a frame up the call stack, its in "C:\w\treesheets\wxWidgets\include\wx/arrstr.h". Farther up the call stack its coming from an event handler. As mentioned before, issue is with image sizes.
```
0:000> r
eax=00000000 ebx=002ee0c0 ecx=047a1f80 edx=00000000 esi=0073320c edi=047a1f80
eip=0043350a esp=0018fbd8 ebp=0018fbe0 iopl=0         nv up ei pl zr na pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00210246
TreeSheets+0x3350a:
0043350a 8b30            mov     esi,dword ptr [eax]  ds:002b:00000000=????????

00433500 55              push    ebp
00433501 8bec            mov     ebp,esp
00433503 56              push    esi
00433504 57              push    edi
00433505 8bf9            mov     edi,ecx
00433507 8b4734          mov     eax,dword ptr [edi+34h]

0:000> dc @ecx
047a1f80  047a2380 0478a6f8 00000000 00000000  .#z...x.........
047a1f90  00000000 00000000 00000000 00000000  ................
047a1fa0  00000000 00000000 00000000 00000000  ................
047a1fb0  04791600 00000000 00000000 00000000  ..y.............
047a1fc0  00000001 00000001 00000000 00000000  ................
047a1fd0  00000000 00000000 00000000 00000000  ................
047a1fe0  00000000 00000000 00000000 00000000  ................
047a1ff0  00000000 00000000 00000000 00000000  ................

0:000> ? @ecx+34
Evaluate expression: 75112372 = 047a1fb4

0:000> kv L8
 # ChildEBP RetAddr  Args to Child              
WARNING: Stack unwind information not available. Following frames may be wrong.
00 0018fbe0 0043a031 0034c334 002c7718 00734de4 TreeSheets+0x3350a
01 0018fbf8 005a6e2f 0477eb30 0018fc24 005a6027 TreeSheets+0x3a031
02 0018fc04 005a6027 002ee0c0 00439f90 00000000 TreeSheets+0x1a6e2f
03 0018fc24 005927d2 002ee0c0 002bb070 0477eb30 TreeSheets+0x1a6027
04 0018fc3c 005923e5 0083f924 002ee0c0 0477eb30 TreeSheets+0x1927d2
05 0018fc5c 00593297 0477eb30 002ee0c0 0477eb30 TreeSheets+0x1923e5
06 0018fc74 005926d2 0477eb30 0477eb30 002ee0c0 TreeSheets+0x193297
07 0018fc8c 00591f9f 0477eb30 e6a769dc 0477eb30 TreeSheets+0x1926d2

0:000> dc @esp L1c
0018fbd8  0034c334 0073320c 0018fbf8 0043a031  4.4..2s.....1.C.
0018fbe8  0034c334 002c7718 00734de4 00000004  4.4..w,..Ms.....
0018fbf8  0018fc04 005a6e2f 0477eb30 0018fc24  ..../nZ.0.w.$...
0018fc08  005a6027 002ee0c0 00439f90 00000000  '`Z.......C.....
0018fc18  0477eb30 002d5538 0477eb30 0018fc3c  0.w.8U-.0.w.<...
0018fc28  005927d2 002ee0c0 002bb070 0477eb30  .'Y.....p.+.0.w.
0018fc38  00000003 0018fc5c 005923e5 0083f924  ....\....#Y.$...

0:000> u 439f90 L14
TreeSheets+0x39f90:
00439f90 55              push    ebp
00439f91 8bec            mov     ebp,esp
00439f93 833dc82c830000  cmp     dword ptr [TreeSheets+0x432cc8 (00832cc8)],0
00439f9a 8b4508          mov     eax,dword ptr [ebp+8]
00439f9d 53              push    ebx
00439f9e 8bd9            mov     ebx,ecx
00439fa0 56              push    esi
00439fa1 57              push    edi
00439fa2 8b784c          mov     edi,dword ptr [eax+4Ch]
00439fa5 8bb34c030000    mov     esi,dword ptr [ebx+34Ch]
00439fab 743a            je      TreeSheets+0x39fe7 (00439fe7)
00439fad 3bbe50030000    cmp     edi,dword ptr [esi+350h]
00439fb3 7232            jb      TreeSheets+0x39fe7 (00439fe7)
00439fb5 6860007300      push    offset TreeSheets+0x330060 (00730060)
00439fba 68a8007300      push    offset TreeSheets+0x3300a8 (007300a8)
00439fbf 6820857200      push    offset TreeSheets+0x328520 (00728520)
00439fc4 68be000000      push    0BEh
00439fc9 6834857200      push    offset TreeSheets+0x328534 (00728534)
00439fce e88deb1600      call    TreeSheets+0x1a8b60 (005a8b60)
00439fd3 83c414          add     esp,14h

0:000> da 728520
00728520  "wxArrayString::Item"

0:000> da 730060
00730060  "w"

0:000> da 728534
00728534  "C:\w\treesheets\wxWidgets\includ"
00728554  "e\wx/arrstr.h"
```

**Comment by aardappel** [comment]
Apologies, I thought you meant it was crashing in the new version. Let me merge it, and see if it works then :)

**Comment by aardappel** [comment]
Ok, the questionmark works fine, just it looks very light on white background. If you look at the nuvola icons, they have a black outline.. would be good if this could match it in style.

**Comment by arizvisa** [comment]
That is very weird, as the .svg looks like:
https://github.com/arizvisa/treesheets/blob/4cf33811fd2e3867ee94bc72c3725c38e71b4ee1/TS/images/question.svg

ImageMagick seems to be cutting out the bevel from the .svg?

**Comment by arizvisa** [comment]
The image was generated by stealing the path (abiding by the license of course) and coloring it yellow from https://commons.wikimedia.org/wiki/File:Orange_question.svg

After that, I added this filter, which should bevel it so one can see a sort of outline on a white background.
```
  <defs>
    <filter style="color-interpolation-filters: sRGB;" id="bevel" width="2.5" x="-0.5" height="1.5" y="-0.5">
      <feMorphology radius="25" in="SourceAlpha" result="bevel-alpha" />
      <feComposite operator="out" in="SourceGraphic" in2="bevel-alpha" result="alpha-graphic-composite"/>
      <feGaussianBlur stdDeviation="0.5" in="alpha-graphic-composite" result="blurred" />
      <feDiffuseLighting diffuseConstant="1.25" surfaceScale="1.5" in="blurred" result="lighted">
        <feDistantLight elevation="35" azimuth="315" />
      </feDiffuseLighting>
      <feBlend mode="multiply" in="SourceGraphic" in2="lighted" result="lighted-graphic-composite" />
      <feComposite operator="in" in="lighted-graphic-composite" in2="SourceAlpha" />
    </filter>
  </defs>
```
I guess I need to find something other than ImageMagick to convert to a transparent .png that can actually comprehend an .svg filter...

**Comment by aardappel** [comment]
That svg does have something of a black border, but only on one side (emulating a lighting effect) which is still very different stylistically from the nuvola icons.

**Comment by arizvisa** [comment]
K. I'll fiddle with these filters some more to try and get a similar appearance.

**Comment by arizvisa** [comment]
@aardappel, how's this one?
https://github.com/arizvisa/treesheets/blob/question-mark-image/TS/images/nuvola/dropdown/maybe.png

**Comment by aardappel** [comment]
That's a lot better! I'd make the bright side even darker though, it doesn't need much "lighting"

**Comment by arizvisa** [comment]
https://github.com/arizvisa/treesheets/commit/005138beea3cccbdb9a7e0e1c0a37903fefca0aa ?

**Comment by arizvisa** [comment]
https://github.com/arizvisa/treesheets/commit/5991472eae84dc453fcac8aaf6dfc0ac9e9306f8?
I tweaked the background path to ensure the whole thing is outlined.

Also I learned that instead of the bevel using a diffuse light, I can add a phong effect to it using a specular light. Does that matter to you at all?

**Comment by aardappel** [comment]
Whatever looks most nuvola like, I guess. Some of them use quite a bit of specular/metallic/glossy, so could look ok.

**Comment by arizvisa** [comment]
Ok. I'll try and fiddle with that part some more when I get off work later.

**Pull request merged**
