### PR TITLE
Add CMake build.

### PR DESCRIPTION
**Pull request by tamaskenez**
Thanks for this great tool!
For me it was easier to build with CMake so I added this script. Feel free to accept or reject.

### CODE REVIEW

**Comment by aardappel** [comment]
Thanks!
Not sure how I feel about relying on the system wxWidgets, since it is often out of date, and of course Windows has no concept of it being installed.
But for now, this doesn't hurt to have also.

**Comment by tamaskenez** [comment]
It's not tied to system wxWidgets, even on Windows the user can build the latest one from sources, install it to a local dir, tell CMake (the FindwxWidgets.cmake module) about that dir and done.

In the meantime I've just tested on ub14, works fine with system wxwidgets 3.0.

**Comment by aardappel** [comment]
Cool, thanks :)

**Comment by ngirard** [comment]
I confirm it's a valuable addition, and it works fine here on Ubuntu 17.04 !

**Pull request merged**
