### PR TITLE
Reorganise selection in `InitWith` code

### PR DESCRIPTION
**Pull request by t2b3**
- Make it more compact.
- When cell found, jump to end of routine instead of looping through the rest of the cells in the grid.

### CODE REVIEW

**Comment by aardappel** [comment]
This changes the logic of whats happening, before, if ipg was null, it wouldn't call SetSelect, now it does, is this intentional?

The new code is harder to follow, so unless breaking the loop is important, it is probably not an improvement.

**Comment by t2b3** [comment]
> This changes the logic of whats happening, before, if ipg was null, it wouldn't call SetSelect, now it does, is this intentional?
> 
> 
> 
> The new code is harder to follow, so unless breaking the loop is important, it is probably not an improvement.
> 
> 

Hi Wouter!
The logic is not inverted. If ipg is nullptr, SetSelected will not be called. And I consider that breaking the loop is an improvement. Can we agree to leave most of it but add the possibility of breaking the loop?
Kind regards

**Comment by aardappel** [comment]
If ipg is null, it calls the SetSelect in the else branch?

**Comment by t2b3** [comment]
> If ipg is null, it calls the SetSelect in the else branch?

Ok this was wrongly expressed. In the else branch there is `SetSelect`, for only for the first cell in the top-left.

**Comment by t2b3** [comment]
On the other side, the case of `ics` evaluating to true and `ipg` evaluating to false (nullptr) is now considered in this PR.

**Comment by t2b3** [comment]
Ok now I got what you meant. Would this be a problem to call `SetSelect` to select the first cell on the top left if `ipg` was `nullptr`?

**Comment by t2b3** [comment]
Ok I agree better  to keep it the old way.

**Comment by t2b3** [comment]
> This changes the logic of whats happening, before, if ipg was null, it wouldn't call SetSelect, now it does, is this intentional?
> 
> The new code is harder to follow, so unless breaking the loop is important, it is probably not an improvement.

Short answer: No, it was not really intentional :-)

**Comment by t2b3** [comment]
Sorry for the noise!

**Pull request closed without merging**
