### PR TITLE
It translation

### PR DESCRIPTION
**Pull request by albanobattistella**

### CODE REVIEW

**Comment by aardappel** [comment]
Grazie!

Il mio italiano e' semplice, ma lo provo:
Grazie per la traduzione! C'e' solamente un piccolo problema: la file che hai modifcato e' un esempio, puoi mettere il tuo file in a `TS/translations/it/ts.po` e mantenere il orginale? Vedi il directory `de` come esempio.

In inglese:
Thanks for the translation! There's one small problem though, the file you renamed needs to remain, as its an example file for future translation.

So keep the original file as `TS/translations/ts.pot`, and put your modified file as `TS/translations/it/ts.po`, see for example the `de` directory.

**Comment by albanobattistella** [comment]
Hi,

your italian is better than mine.!  ;-)

i'll trie...because I'm not an expert..about it.

thanks..

Albano

________________________________
Da: Wouter van Oortmerssen <notifications@github.com>
Inviato: domenica 19 maggio 2019 16:51
A: aardappel/treesheets
Cc: albanobattistella; Author
Oggetto: Re: [aardappel/treesheets] It translation (#119)


Grazie!

Il mio italiano e' semplice, ma lo provo:
Grazie per la traduzione! C'e' solamente un piccolo problema: la file che hai modifcato e' un esempio, puoi mettere il tuo file in a TS/translations/it/ts.po e mantenere il orginale? Vedi il directory de come esempio.

In inglese:
Thanks for the translation! There's one small problem though, the file you renamed needs to remain, as its an example file for future translation.

So keep the original file as TS/translations/ts.pot, and put your modified file as TS/translations/it/ts.po, see for example the de directory.

**Comment by aardappel** [comment]
That's ok, I can fix the renaming for you

**Comment by aardappel** [comment]
Fixed some things in the file here (quotation marks etc): https://github.com/aardappel/treesheets/commit/69be960f97b11dda7d498ebd861a8de5b598c077

**Comment by albanobattistella** [comment]
Thanks! If you Need help letto me know!
V/r,
Albano
________________________________
Da: Wouter van Oortmerssen <notifications@github.com>
Inviato: domenica 19 maggio 2019 21:20:23
A: aardappel/treesheets
Cc: albanobattistella; Author
Oggetto: Re: [aardappel/treesheets] It translation (#119)


That's ok, I can fix the renaming for you

**Pull request merged**
