### PR TITLE
Add selection cycle

### PR DESCRIPTION
**Pull request by t2b3**
Jump to the opposite side of the grid at the grid border

### CODE REVIEW

**Comment by t2b3** [comment]
https://github.com/aardappel/treesheets/assets/3286756/9824fb20-ec4d-44ba-9c43-18f09762b09c

**Comment by aardappel** [comment]
I am not sure if I'd agree this is a good feature. I very often hold down a direction key to get to the edges of a grid, so I can insert new cells there. I am not sure that being able to wrap around is more useful?

**Comment by t2b3** [comment]
> I am not sure if I'd agree this is a good feature. I very often hold down a direction key to get to the edges of a grid, so I can insert new cells there. I am not sure that being able to wrap around is more useful?

Well, you can still add the new cells because the grid edge needs to be first selected before a wrap can happen. Only when you are in thin selection of the edge and then press the key to leave the grid, then it is wrapped.

**Comment by aardappel** [comment]
Ah I didn't understand that it worked that way from the code ;)
Ok, that could be an improvement then, lets try it out!

**Comment by t2b3** [comment]
> Ah I didn't understand that it worked that way from the code ;)
> 
> Ok, that could be an improvement then, lets try it out!

Thanks for your reply and the merge!

**Pull request merged**
