### PR TITLE
With WxWidgets, Unicode seems to be the default and there appears to …

### PR DESCRIPTION
**Pull request by owencook**
…be no optimization option

### CODE REVIEW

**Comment by aardappel** [comment]
I'm not sure what you're trying to accomplish here.. you think we should turn off unicode and optimization?

**Comment by aardappel** [comment]
Ok, I see.
There are now 2 binary files in your commit, can you remove them?
You can also remove the description of the missing flags from the readme. I only wanted to know why they were removed here on this PR.

**Comment by owencook** [comment]
Apologies for the binaries, they are now removed.  GIT ignorance on my part.

**Comment by aardappel** [comment]
Ok, thanks!

**Pull request merged**
