### PR TITLE
Replace replace all icon

### PR DESCRIPTION
**Pull request by tobiolo**
Proposal for a replacement:
It is like the replace icon but within the document icon.

### CODE REVIEW

**Comment by aardappel** [comment]
Neither is great, the old one looks like "search again", and the new one is hard to even see what it is. So I don't mind either one, your call.

Not sure what would be better.. I don't see any good icons online.

**Comment by tobiolo** [comment]
> Neither is great, the old one looks like "search again", and the new one is hard to even see what it is. So I don't mind either one, your call.
> 
> 
> 
> Not sure what would be better.. I don't see any good icons online.

You are right. Better try something more readable!

**Comment by georgeraraujo** [comment]
What do you think of https://github.com/microsoft/vscode-icons/blob/main/icons/light/replace-all.svg ?

As far as I can tell, the license permits use in other projects: https://github.com/microsoft/vscode-icons/blob/main/LICENSE

**Comment by aardappel** [comment]
I guess that is pretty good.. looks a bit like the one that used to be in visual studio I think?

**Comment by georgeraraujo** [comment]
> I guess that is pretty good.. looks a bit like the one that used to be in visual studio I think?

It is used in Visual Studio Code, so it could be.

**Comment by georgeraraujo** [comment]
I replaced the current icons with the ones from https://github.com/microsoft/vscode-icons/ - I modified them to be all black for more contrast, and created edit/copy and edit/paste from existing icons:

image

What do you think?

**Comment by aardappel** [comment]
Those icons are pretty good.. but maybe we can use a version with slighty thinner lines?

My VSCode looks like:

image

**Comment by georgeraraujo** [comment]
> Those icons are pretty good.. but maybe we can use a version with slighty thinner lines?
> 
> My VSCode looks like:
> 
> image

I think the lines in my screenshot look thicker because I changed the grayish color in the stock VSCode icons to black. Here's how TreeSheets looks like with the stock VSCode icons (except for Paste, New Grid, and Image, for which VSCode had no corresponding icons):

image

**Comment by aardappel** [comment]
By changing them to black you also changed the edge pixels which presumably had an alpha component, making it look thicker.

So yeah, thinner looks better, but you'd need icons for Paste etc that look the same.

**Comment by georgeraraujo** [comment]
> By changing them to black you also changed the edge pixels which presumably had an alpha component, making it look thicker.
> 
> So yeah, thinner looks better, but you'd need icons for Paste etc that look the same.

Here's what I came up with:

image

**Comment by aardappel** [comment]
looks nice to me, wdyt @tobiolo

**Comment by tobiolo** [comment]
Hi @georgeraraujo, @aardappel 
I like that icon set very much. Thus I would love to see a PR landing. 😄 Thanks for your work @georgeraraujo

**Comment by georgeraraujo** [comment]
> Hi @georgeraraujo, @aardappel I like that icon set very much. Thus I would love to see a PR landing. 😄 Thanks for your work @georgeraraujo

https://github.com/aardappel/treesheets/pull/641

**Pull request closed without merging**
