### PR TITLE
Use icons from Visual Studio Code in the toolbar

### PR DESCRIPTION
**Pull request by georgeraraujo**

### CODE REVIEW

**Comment by tobiolo** [comment]
Thanks for your PR and the updated icon set!

**Comment by georgeraraujo** [comment]
I thought the New Grid icon could be more descriptive, so I came up with this:

image

What do you think, @aardappel @tobiolo ?

**Comment by aardappel** [comment]
looks nice :)

**Comment by tobiolo** [comment]
> looks nice :)

I agree!

**Comment by georgeraraujo** [comment]
I further refined New Grid and Add Image to harmonize with the other icons. If you like this, I can submit a PR:

image

**Pull request merged**
