### PR TITLE
Expose Text filtered on Script Interface for Lobster

### PR DESCRIPTION
**Pull request by tobiolo**

### CODE REVIEW

**Comment by tobiolo** [comment]
Not so sure about the boolean data types.
Especially in the use case that it is first checked for filtered and depending on the result the text filtered is set or not.

**Comment by tobiolo** [comment]
This might be a first step to move all the view filter options into scripts...

**Comment by aardappel** [comment]
That is fine, in Lobster, `bool` is an enum which is a subtype of `int`

**Comment by tobiolo** [comment]
> That is fine, in Lobster, `bool` is an enum which is a subtype of `int`

Ah, thanks! 😄

**Pull request merged**
